Lab.Demo.EF.WebApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using Lab.Demo.EF.WebApi.Areas.HelpPage.ModelDescriptions;

namespace Lab.Demo.EF.WebApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

Lab.Demo.EF.WebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Lab.Demo.EF.WebApi.Areas.HelpPage.ModelDescriptions;
using Lab.Demo.EF.WebApi.Areas.HelpPage.Models;

namespace Lab.Demo.EF.WebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Lab.Demo.EF.WebApi/Controllers/BootController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Demo.EF.WebApi.Controllers
{
    public class BootController : Controller
    {
        // GET: Boot
        public ActionResult Index()
        {
            return View();
        }
    }
}

Lab.Demo.EF.WebApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Demo.EF.WebApi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
        public ActionResult Index2()
        {

            return View();
        }  
    }
}

Lab.Demo.EF.WebApi/Controllers/KnockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Demo.EF.WebApi.Controllers
{
    public class KnockController : Controller
    {
        // GET: Knock
        public ActionResult Index()
        {
            return View();
        }
    }
}

Lab.Demo.EF.WebApi/Controllers/RegionController.cs
using Lab.Demo.EF.Entities;
using Lab.Demo.EF.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Demo.EF.MVC.Controllers
{
    public class RegionController : Controller
    {
        public RegionLogic logic = new RegionLogic();

        public ActionResult Index()
        {

            var regions = logic.GetAll();

            return View(regions);

        }
        public ActionResult UpdateForm(int id)
        {

           var reg = logic.GetOne(id);

            return View(reg);

        }


        public ActionResult Update(Region region)
        {

            logic.Update(region);

            return RedirectToAction("Index");
        }

        public ActionResult CreateForm()
        {

            return View();
        }


        public ActionResult Create(Region region)
        {
            logic.Add(region);

            return RedirectToAction("Index");
        }

        public ActionResult DeleteForm(int id)
        {
            var reg = logic.GetOne(id);

            return View(reg);
        }


        public ActionResult Delete(Region region)
        {

            var regiondelete = logic.GetOne(region.RegionID);

            logic.Delete(regiondelete);

            return RedirectToAction("Index");
        }

    }
}

Lab.Demo.EF.WebApi/Views/Boot/Index.cshtml
<h2>Get All</h2>

<table class="table" id="Tabla">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Region</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div class="row">
    <div class="col-md-5">
        <h2>Editar Region</h2>

        <div class="form-group">
            <label>Region ID</label>
            <input type="text" id="RegionID" class="form-control" />
        </div>
        <div class="form-group">
            <label>Region Descripcion</label>
            <input type="text" id="RegionDescripcion" class="form-control" readonly="readonly" />
        </div>
        <div class="form-group">
            <button class="btn btn-primary" id="btn-ajax-get">Obtener Region</button>
            <button class="btn btn-primary" id="btn-ajax-update">Guardar Region</button>
        </div>
    </div>
    <div class="col-md-5">
        <h2>Crear Region</h2>

        <div class="form-group">
            <label>Ingrese ID</label>
            <input type="text" id="CreateRegionID" class="form-control" />
        </div>

        <div class="form-group">
            <label>Ingrese Descripcion</label>
            <input type="text" id="CreateRegionDescripcion" class="form-control" />

        </div>
        <div class="form-group">
            <button class="btn btn-primary" id="btn-ajax-create">Crear Region</button>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {

        $('#btn-ajax-get').on('click', ajaxGet);
        $('#btn-ajax-create').on('click', ajaxCreate);
        $('#btn-ajax-update').hide();
        $('#btn-ajax-update').on('click', ajaxUpdate);
        getAll();

    });

    function getAll() {



        $.getJSON("/api/region/", function (data) {
            for (let item of data) {

                $("#Tabla tbody").append(`
                    <tr>
                        <th id="`+item.RegionID+`">`+item.RegionID+`</th>
                        <td id="`+item.RegionID+`">`+item.RegionDescription.trim()+`</td>
                        <td>
                            <button class="btn btn-warning" onclick="edit(`+ item.RegionID+`,'`+item.RegionDescription.trim()+`')" id="btn-editar">Editar</button>
                            <button class="btn btn-danger" onclick="ajaxDelete(`+ item.RegionID +`)">Eliminar</button>
                       </td>
                    </tr>`);   
            }
        });
    }

    function edit(regionID,regionDescripcion) {

        $("td" + "#" + regionDescripcion).html('<input type="text" class="form-control" id="' + regionID + '">"')
        $("td" + "#" + regionDescripcion).remove
        $("#btn-editar").removeAttr("onclick")
        $("#btn-editar").text("Guardar")
        $("#btn-editar").attr("class", "btn btn-success")
        $("#btn-editar").attr("onclick", "editar("+regionID+")")        
    }

    function editar(region) {
            var model = {
            RegionID: tregionID,
            RegionDescription: $("input " + "#" + item.RegionDescription).val()
        }

        $.ajax({

            url: '/api/region/',
            method: 'PUT',
            data: model,

            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
        }


    function ajaxUpdate() {

        var model = {
            RegionID: $('#RegionID').val(),
            RegionDescription: $('#RegionDescripcion').val()
        }



        $.ajax({

            url: '/api/region/',
            method: 'PUT',
            data: model,

            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })

    }

    function ajaxGet() {

        idReg = $('#RegionID').val();

        $.getJSON("/api/region/"+idReg, function (data) {
            $('#RegionID').val(data.RegionID);
            $('#RegionDescripcion').val(data.RegionDescription);
            $('#btn-ajax-update').show();
            $('#RegionDescripcion').removeAttr("readonly")
            $('#RegionID').attr("readonly", "readonly")

        });
    }



    function ajaxDelete(regionID) {

        $.ajax({

            url: '/api/region/'+regionID,
            method: 'DELETE',
            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }

    function ajaxCreate() {

        var model = {
            RegionID: $('#CreateRegionID').val(),
            RegionDescription: $('#CreateRegionDescripcion').val()
        }



        $.ajax({

            url: '/api/region/',
            method: 'POST',
            data: model,

            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }


</script>

Lab.Demo.EF.WebApi/Views/Home/Index.cshtml
<h2>Get All</h2>

    <table id="Table-Regions" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>Descripcion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div class="row">
        <div class="col-md-5">
            <h2>Editar Region</h2>

            <div class="form-group">
                <label>Region ID</label>
                <input type="text" id="RegionID" class="form-control" />
            </div>
            <div class="form-group">
                <label>Region Descripcion</label> 
                <input type="text" id="RegionDescripcion" class="form-control" readonly="readonly" />
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="btn-ajax-get">Obtener Region</button>
                <button class="btn btn-primary" id="btn-ajax-update">Guardar Region</button>
            </div>
        </div>
        <div class="col-md-5">
            <h2>Crear Region</h2>

            <div class="form-group">
                <label>Ingrese ID</label>
                <input type="text" id="CreateRegionID" class="form-control" />
            </div>

            <div class="form-group">
                <label>Ingrese Descripcion</label>
                <input type="text" id="CreateRegionDescripcion" class="form-control" />

            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="btn-ajax-create">Crear Region</button>
            </div>
        </div>
    </div>
    <script>

    $(document).ready(function () {

        $('#btn-ajax-get').on('click', ajaxGet);

        $('#btn-ajax-create').on('click', ajaxCreate);

        $('#btn-ajax-update').hide();

        $('#btn-ajax-update').on('click', ajaxUpdate);

        getAll();

    });

    function getAll() {



        $.getJSON("/api/region/", function (data) {


            for (let item of data) {

                $("#Table-Regions tbody").append("<tr><td>" + item.RegionID + "</td><td>" + item.RegionDescription.trim() + '</td><td><button class="btn btn-danger" onclick="ajaxDelete(' + item.RegionID + ')">Eliminar</button></td></tr>')

            }
            $('#Table-Regions').DataTable();

        });


    }

    function ajaxUpdate() {

        var model = {
            RegionID: $('#RegionID').val(),
            RegionDescription: $('#RegionDescripcion').val()
        }



        $.ajax({

            url: '/api/region/',
            method: 'PUT',
            data: model,

            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })

    }

    function ajaxGet() {

        idReg = $('#RegionID').val();

        $.getJSON("/api/region/"+idReg, function (data) {
            $('#RegionID').val(data.RegionID);
            $('#RegionDescripcion').val(data.RegionDescription);
            $('#btn-ajax-update').show();
            $('#RegionDescripcion').removeAttr("readonly")
            $('#RegionID').attr("readonly", "readonly")

        });
    }



    function ajaxDelete(regionID) {

        $.ajax({

            url: '/api/region/'+regionID,
            method: 'DELETE',
            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }

    function ajaxCreate() {

        var model = {
            RegionID: $('#CreateRegionID').val(),
            RegionDescription: $('#CreateRegionDescripcion').val()
        }



        $.ajax({

            url: '/api/region/',
            method: 'POST',
            data: model,

            success: function () {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }


    </script>

Lab.Demo.EF.WebApi/Views/Knock/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Descripcion</th>

        </tr>
    </thead>
    <tbody data-bind="foreach: regionList">
        <tr>
            <th data-bind="text: RegionID"></th>
            <th data-bind="text: RegionDescription"></th>
        </tr>
    </tbody>
</table>


<script>

    var ViewModel = function () {

        self = this;
        self.getAll = function () {
            var origin = window.location.origin;
            $.getJSON(origin+'/api/region/', function (data) {
                self.regionList(data);
            })

        }

        self.regionList = ko.observableArray();

    }

    

    $(document).ready(function () {

       var vModel = new ViewModel()

        ko.applyBindings(vModel)

        vModel.getAll();
});

</script>

Lab.Demo.EF.WebApi/Views/Region/CreateForm.cshtml
@model Lab.Demo.EF.Entities.Region

@{
    ViewBag.Title = "Create";
}

<h2>Crear Nueva Region</h2>

@using (Html.BeginForm("Create", "Region", FormMethod.Post))
{
    <div class="form-group">
        <label>Ingrese ID</label>
        @Html.TextBoxFor(m => m.RegionID, new {@class = "form-control"})
    </div>

    <div class="form-group">
        <label>Ingrese Descripcion</label>
        @Html.TextBoxFor(m => m.RegionDescription, new {@class = "form-control"})

     </div>
        <button type="submit" class="btn btn-primary">Crear Region</button>
        }

<br /><br />

<button class="btn btn-primary" id="btn-ajax">Crear Region con Ajax</button>

<script>

    $(document).ready(function () {

        $('#btn-ajax').on('click', ajaxCreate);
    });

    function ajaxCreate() {

        var model = {
            RegionID: $('#RegionID').val(),
                RegionDescription: $('#RegionDescription').val()
        }

        $.ajax({

            url: '@Url.Action("Create")',
            method: 'POST',
            data: { region: model },

            success: function (data) {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }


</script>

Lab.Demo.EF.WebApi/Views/Region/DeleteForm.cshtml
@model Lab.Demo.EF.Entities.Region
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
@using (Html.BeginForm("Delete", "Region", FormMethod.Post))
{
    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(m => m.RegionID, new { @readonly = "readonly", @class = "form-control" })
        <br />
        <label>Descripcion</label>
        @Html.TextBoxFor(m => m.RegionDescription, new { @readonly = "readonly", @class = "form-control" })
</div>

    <button type="submit" class="btn btn-danger">Eliminar Region</button>
}

<br />
<br />

<button class="btn btn-primary" id="btn-ajax">Eliminar Region con Ajax</button>

<script>

    $(document).ready(function () {

        $('#btn-ajax').on('click', ajaxDelete);
    });

    function ajaxDelete() {

        var model = {
            RegionID: $('#RegionID').val(),
                RegionDescription: $('#RegionDescription').val()
        }

        $.ajax({

            url: '@Url.Action("Delete")',
            method: 'POST',
            data: { region: model },

            success: function (data) {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }


</script>

Lab.Demo.EF.WebApi/Views/Region/Index.cshtml
@model IEnumerable<Lab.Demo.EF.Entities.Region>
@{ 
    ViewBag.Title = "Index";
}

<h3>Regiones</h3>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Descripción</th>
            <th scope="col">Acciones</th>
            <th scope="col">Acciones con Ajax</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
<tr>
    <td name="RegionID" id="@Html.DisplayFor(modelItem => item.RegionID)">
        @Html.DisplayFor(modelItem => item.RegionID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RegionDescription)
    </td>

    <td>
        @Html.ActionLink("Editar", "UpdateForm", new { id = item.RegionID }, new { @class = "btn btn-warning" })
        @Html.ActionLink("Eliminar", "DeleteForm", new { id = item.RegionID }, new { @class = "btn btn-danger" })
    </td>

    <td>
        <button class="btn btn-warning" id="btn-ajax-update" onclick="">Editar con Ajax</button>
        <button class="btn btn-danger" id="btn-ajax-delete" onclick="ajaxDelete(@Html.DisplayFor(modelItem => item.RegionID),'@Html.DisplayFor(modelItem => item.RegionDescription)')">Eliminar con Ajax</button>
    </td>

</tr>
    }
</table>

@Html.ActionLink("Create", "CreateForm", null, new { @class = "btn btn-primary"})


<script>


    function ajaxDelete(regionID, regionDescripcion) {


        var model = {

            RegionID: regionID,
                RegionDescription: regionDescripcion
        }

        $.ajax({

            url: '@Url.Action("Delete")',
            method: 'POST',
            data: { region: model },

            success: function (data) {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }

</script>

Lab.Demo.EF.WebApi/Views/Region/UpdateForm.cshtml
@model Lab.Demo.EF.Entities.Region
@{
    ViewBag.Title = "Region Update";
}

<h3>Region Update</h3>

@using (Html.BeginForm("Update", "Region", FormMethod.Post))
{

    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(m => m.RegionID, new { @readonly = "readonly", @class = "form-control" })

    </div>
    <div class="form-group">
        <label>Descripcion</label>
        @Html.TextBoxFor(m => m.RegionDescription, new { @readonly = "readonly", @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Ingrese Nueva Descripcion</label>
        @Html.TextBoxFor(m => m.RegionDescription, new { @class = "form-control", id = "RegionDescriptionNueva"})
    </div>

    <button type="submit" class="btn btn-primary">Actualizar</button>


}

<br />
<br />

<button class="btn btn-primary" id="btn-ajax">Editar Region con Ajax</button>

<script>

    $(document).ready(function () {

        $('#btn-ajax').on('click', ajaxUpdate);
    });

    function ajaxUpdate() {

        var model = {
            RegionID: $('#RegionID').val(),
                RegionDescription: $('#RegionDescriptionNueva').val()
        }

        $.ajax({

            url: '@Url.Action("Update")',
            method: 'POST',
            data: { region: model },

            success: function (data) {
                window.location.href = "@Url.Action("Index")";
            },
            error: function () {
                alert('Nop')
            }

        })
    }


</script>

Lab.Demo.EF.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API Help", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Region", "Index", "Region", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Boot", "Index", "Boot", new { area = "" }, null)</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>